#!/usr/bin/env sh

. ./setup-utilities

if [ -f ./first-time ]
then
	echo
	echo Check setup-first-time for important hints
	echo
else
	echo
	echo First time: check setup-first-time for important hints
	. ./setup-first-time
fi

#. ./setup-docker -> setup-first-time
. ./setup-system-fish
. ./setup-system-flatpak
#. ./setup-system-fonts
. ./setup-system-i3
. ./setup-system-polybar
. ./setup-system-kitty
#. ./setup-dev-nix
#. ./setup-dev-nodejs
#. ./setup-dev-nvim

