#!/usr/bin/env sh
echo setup-system-i3

# Includes setup-utilities only for standalone (directly calling)
# use of this script (otherwise the script is called from setup
# and the import is not necessary)
if [ $0 ]
then
. ./setup-utilities
fi

setup() {
  install_packages $@

  REPOS=(picom dunst i3 maim nitrogen polybar rofi)
  repos "${REPOS[@]}"
}

#https://wiki.archlinux.org/title/i3
#https://dev.to/l04db4l4nc3r/compositors-in-linux-1hhb
#https://wiki.archlinux.org/title/Picom

PACKAGES=(desktop-i3)
setup "${PACKAGES_I3[@]}"

