#!/usr/bin/env sh
echo setup-utilities

# https://www.tutorialspoint.com/unix/unix-basic-operators.htm

SETUP_DIR=$HOME/Me/system/setup
BIN_DIR=$HOME/.local/bin
XDG_CONFIG_HOME=$HOME/.config

cd_to_do() {
  cd $XDG_CONFIG_HOME/$1
	echo_pwd
	
	list=("$@")
	list=("${list[@]:1}")

  for do in "${list[@]}"; do
		eval $do
		#echo $PWD
	done
	
  cd $SETUP_DIR
  echo_pwd
}

echo_pwd() {
	echo
	echo -e "\t - now in ${PWD}"
	echo
}

exists() { type -t "$1" > /dev/null 2>&1; }

# https://stackoverflow.com/questions/3074288/get-final-url-after-curl-is-redirected#comment71496988_5300429
finalurl() { curl --silent --location --head --output /dev/null --write-out '%{url_effective}' -- "$@"; }

git_remote_url_reachable() {
  git ls-remote "$1" CHECK_GIT_REMOTE_URL_REACHABILITY &>/dev/null
}

install_packages () {
  # https://askubuntu.com/a/674347
  #local list=("$@")
  list=("$@")
  
  for PACKAGE in "${list[@]}"; do
  	INSTALLED=$(sudo swupd bundle-info $PACKAGE | grep Status | cut -d' ' -f2)
    if [[ $INSTALLED =~ "Not" ]]
    then
      sudo swupd bundle-add $PACKAGE
    else
    	echo "Bundle ${PACKAGE} already installed"
    fi
  done
}

not_exists_dir() { 
  [ ! -d $1 ]
}

repos() {
  list=("$@")

  for repo in "${list[@]}"; do
    repo_operations ${repo}
  done
}

single_repo() {
  URL=${1}
  repo=${2}
  
  repo_operations ${repo} ${URL}
}

repo_operations() {
  cd $XDG_CONFIG_HOME

	repo=$1
	URL=${2-https://github.com/maxdevjs/dotfiles-${repo}-config}
	
  if not_exists_dir $XDG_CONFIG_HOME/$repo
  then
    # https://superuser.com/a/1415376
    if git_remote_url_reachable "$URL"; then
    	echo "cloning ${URL} to ${repo}"
      git clone $URL ${repo}
    else
      echo -e "\n\tApparently ${URL} does not exists (or it is not reachable at the moment)\n\tRemember to check it manually."
      echo
    fi
  else
    cd $XDG_CONFIG_HOME/$repo
    echo -e "\t$PWD\n\tChecking if $repo is up-to-date, otherwise pulling updates."
    git pull
    echo
  fi
  
  cd $SETUP_DIR
}

# https://stackoverflow.com/a/37939589 
version() { echo "$@" | awk -F. '{ printf("%d%03d%03d%03d\n", $1,$2,$3,$4); }'; }

if [ ! -d "$BIN_DIR" ]; then
  mkdir -p $BIN_DIR
fi

#cp ./.local/share/applications/restart-budgie.desktop ~/.local/share/applications/
