#!/usr/bin/env sh
echo setup-dev-docker

# Includes setup-utilities only for standalone (directly calling)
# use of this script (otherwise the script is called from setup
# and the import is not necessary)
if [ $0 ]
then
. ./setup-utilities
fi

function setup () {
  if ! exists docker; then
    #sudo swupd bundle-add containers-basic docker-compose
    PACKAGES_DOCKER=(containers-basic docker-compose)
    install_packages "${PACKAGES_DOCKER[@]}"

    # https://www.docker.com/products/docker-desktop/
    # https://docs.docker.com/desktop/install/linux-install/
    # sudo swupd bundle-add qemu-guest-additions
  
    # AppArmor
    # https://docs.docker.com/engine/install/binaries/
        
    # https://docs.docker.com/engine/install/linux-postinstall/
    # Manage Docker as a non-root user
    # https://github.com/docker/kitematic/issues/2528
    # https://docs.docker.com/engine/install/linux-postinstall/#manage-docker-as-a-non-root-user
    # https://stackoverflow.com/questions/49434650/how-to-add-a-user-to-a-group-without-logout-login-bash-script
    # https://superuser.com/questions/272061/reload-a-linux-users-group-assignments-without-logging-out#comment1036933_609141
    sudo groupadd docker
    sudo usermod -aG docker $USER
    newgrp docker #&& exec sudo su -l $USER
    
    # https://stackoverflow.com/a/51362528
    sudo chmod 666 /var/run/docker.sock

    sudo chown "$USER":"$USER" /home/"$USER"/.docker -R
    sudo chmod g+rwx "$HOME/.docker" -R
    
    docker run hello-world

    # In case: https://discuss.getsol.us/d/3157-docker-not-running/3
    #sudo rm -rf /var/lib/docker/overlay
    
  fi
  
  if [[ systemctl status docker.service | grep disabled ]]
  then
    # https://docs.docker.com/engine/install/linux-postinstall/#configure-docker-to-start-on-boot
    sudo systemctl enable docker.service
		sudo systemctl enable containerd.service
		
		sudo systemctl start docker.service
		sudo systemctl start containerd.service
	fi
}

setup
